<a href="https://colab.research.google.com/github/aaryanrajput26/Deep-Learning/blob/main/DL_exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("NumPy 1D:\n", a1)
print("NumPy 2D:\n", a2)
print("NumPy 3D:\n", a3)


NumPy 1D:
 [1 2 3]
NumPy 2D:
 [[1 2 3]
 [4 5 6]]
NumPy 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])
t3 = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("PyTorch 1D:\n", t1)
print("PyTorch 2D:\n", t2)
print("PyTorch 3D:\n", t3)


PyTorch 1D:
 tensor([1, 2, 3])
PyTorch 2D:
 tensor([[1, 2, 3],
        [4, 5, 6]])
PyTorch 3D:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


element wise operation

In [16]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)


Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


dot product

In [17]:
print("NumPy Dot:", np.dot([1, 2, 3], [4, 5, 6]))
print("PyTorch Dot:", torch.dot(torch.tensor([1,2,3]), torch.tensor([4,5,6])))



NumPy Dot: 32
PyTorch Dot: tensor(32)


matrix multiplication

In [18]:
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])

print("Matrix Multiplication:\n", A @ B)


Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])


Indexing and slicing

In [19]:
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print("Element:", t[0, 1])
print("Column:", t[:, 1])
print("Row:", t[1, :])


Element: tensor(20)
Column: tensor([20, 50])
Row: tensor([40, 50, 60])


boolean masking


In [20]:
x = torch.tensor([1, 2, 3, 4, 5])
mask = x > 3
print(x[mask])


tensor([4, 5])


In [21]:
x = np.array([1,2,3,4,5])
print(x[x > 3])


[4 5]


extracting sub tensors


In [22]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

sub = t[0:2, 1:3]
print(sub)

tensor([[2, 3],
        [5, 6]])


reshaping


In [23]:
x = torch.arange(6)

print("View:\n", x.view(2, 3))
print("Reshape:\n", x.reshape(2, 3))

x1 = torch.tensor([1,2,3])
print("Unsqueeze(0):", x1.unsqueeze(0))
print("Unsqueeze(1):", x1.unsqueeze(1))
print("Squeeze:", x1.unsqueeze(0).squeeze())


View:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Reshape:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Unsqueeze(0): tensor([[1, 2, 3]])
Unsqueeze(1): tensor([[1],
        [2],
        [3]])
Squeeze: tensor([1, 2, 3])


In [24]:
x = np.arange(6)
print("NumPy Reshape:\n", x.reshape(2, 3))


NumPy Reshape:
 [[0 1 2]
 [3 4 5]]


Broadcasting


In [25]:
A = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([10,20,30])

print("Broadcasting Result:\n", A + b)


Broadcasting Result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


In-place vs Out-of-place

In [26]:
x = torch.tensor([1,2,3])
y = x + 1
print("Out-of-place:", y)

x.add_(1)
print("In-place:", x)


Out-of-place: tensor([2, 3, 4])
In-place: tensor([2, 3, 4])
